/**
  * Generated by smali2java 1.0.0.558
  * Copyright (C) 2013 Hensence.com
  */

package cn.com.protruly.filemanager.utils;

import java.util.concurrent.Executor;
import android.net.Uri;

import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;

import android.os.Build;
import android.provider.MediaStore;

public class GlobalConstants {

    public static final Executor CATEGORY_EXECUTOR = Executors.newFixedThreadPool(0x1);
    public static final ExecutorService GET_STORAGE_LIST_EXECUTOR = Executors.newFixedThreadPool(0x1);
    //public static final long PHONE_ROM_CAPACITY = Util.getPhoneRomSpace();
    //public static final long PHONE_STORAGE_TOTAL_CAPACITY = Util.getPhoneStorageCapacity();
    //public static final String PHONE_STORAGE_PATH = Util.getPhoneStoragePath();
    //public static final String SD_STORAGE_PATH = Util.getSdStoragePath();
    //public static final String OTG_STORAGE_PATH = Util.getOtgStoragePath(mContext);
    public static final Uri FILES_URI = MediaStore.Files.getContentUri("external");
    public static final Uri MUSIC_URI = MediaStore.Audio.Media.getContentUri("external");
    public static final Uri VIDEO_URI = MediaStore.Video.Media.getContentUri("external");
    public static final Uri PICTURE_URI = MediaStore.Images.Media.getContentUri("external");

    //public static boolean showHiddenFiles = false;

    public static final int PATH_FRAGMENT = 1;
    public static final int SECTION_TYPE =10;

    /* TMP_DIRECTORY_FOR_TEST is Just for test */
    public static final String TMP_DIRECTORY_FOR_TEST = "/sdcard";

    public static final boolean DEBUG = false;

    public static final String NEW_PATHLIST_FRAGMENT = "new_path_list_fragment_info";
    public static final String IS_SELECT_PATH = "is_select_path";
    public static final String FROM_SEARCH = "from_search";
    public static final String OPERATION_TYPE = "operation_type";
    public static final String OPERATION_DATA = "operation_data";
    public static final String PROTRULY_ACTION_GET_CONTENT = "cn.protruly.action.get.content";
    public static final long NOW = System.currentTimeMillis()/1000;
    public static final long DAY_TIME = NOW - 24*60*60;
    public static final long TREDAY_TIME = NOW - 3*24*60*60;
    public static final long WEEK_TIME = NOW - 7*24*60*60;
    public static final String MODE_PATH = "mode_path";
    public static final int MODE_PATH_VIEW = 2;
    public static final int MODE_PATH_SELECT = 3;
    public static final boolean isSupportFileProviderForSdkN = Build.VERSION.SDK_INT >= 24;

    public static final String FILE_PROVIDER_AUTHORITY = "cn.com.protruly.filemanager.fileprovider";

    public static final int SEND_LIMIT = 20;
}
